#!/bin/bash
# Copyright (C) 2022  Santiago Previotto
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# \file docker
docker run --rm -dit \
    --privileged \
    --name avr_toolchain \
    -v /dev/bus/usb:/dev/bus/usb \
    -w $(pwd) \
    -u $(id -u):$(id -g) \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    --group-add=sudo \
    --group-add=tty \
    --group-add=dialout \
    -v $(pwd):$(pwd) \
    santipreviotto/avr_toolchain:lastest \
    /bin/bash

docker exec -it avr_toolchain bash

docker stop avr_toolchain
